const init = async () => {
    try {
        
    } catch (error) {
        console.error(error)
        console.log("Hubo un error");
    }
}

init()